apiVersion: v1
kind: Service
metadata:
  name: prometheus-clusterip-service
  namespace: numaflow-system
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 30900   
    protocol: TCP
    targetPort: 9090
  selector:
    prometheus: prometheus