apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: numaflow-system
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector: 
    matchLabels:
      app: frontend
  resources:
    requests:
      memory: 300Mi